// Tests that the menu-bar artboard's attention and recovery text clears WCAG AA on its translucent menu.

import Foundation
import Testing

@testable import Uttrflow

/// The WCAG relative luminance of an sRGB hex.
private func luminance(_ hex: UInt32) -> Double {
    let channels = [(hex >> 16) & 0xFF, (hex >> 8) & 0xFF, hex & 0xFF].map { Double($0) / 255 }
    let linear = channels.map { $0 <= 0.039_28 ? $0 / 12.92 : pow(($0 + 0.055) / 1.055, 2.4) }
    return 0.2126 * linear[0] + 0.7152 * linear[1] + 0.0722 * linear[2]
}

/// The WCAG contrast ratio between two sRGB hexes, lighter over darker.
private func ratio(_ first: UInt32, _ second: UInt32) -> Double {
    let (a, b) = (luminance(first), luminance(second))
    return (max(a, b) + 0.05) / (min(a, b) + 0.05)
}

/// `top` drawn at `alpha` over `bottom`, channel by channel.
private func composite(_ top: UInt32, alpha: Double, over bottom: UInt32) -> UInt32 {
    [16, 8, 0].reduce(0) { total, shift in
        let t = Double((top >> UInt32(shift)) & 0xFF)
        let b = Double((bottom >> UInt32(shift)) & 0xFF)
        let v = UInt32((t * alpha + b * (1 - alpha)).rounded())
        return total | (v << UInt32(shift))
    }
}

@Suite("The menu-bar artboard's text colours clear WCAG AA on the menu surface")
struct MenuBarArtboardContrastTests {
    /// The menu's translucent layer and the three declared gradient stops.
    private static let menuAlpha = 0.72
    private static let menuFill: UInt32 = 0xFA_FAFD
    private static let brightestStop: UInt32 = 0x6E_909E
    private static let middleStop: UInt32 = 0x44_6370
    private static let darkestStop: UInt32 = 0x27_3840

    private static func background(forStop stop: UInt32) -> UInt32 {
        composite(menuFill, alpha: menuAlpha, over: stop)
    }

    /// Every `style="color:#RRGGBB"` in the attention menu; dots use `background:` and do not count.
    private static func attentionInks(in source: String) -> [UInt32] {
        let marker = "<div class=\"menu\">"
        guard let readyStart = source.range(of: marker),
            let attentionStart = source.range(of: marker, range: readyStart.upperBound..<source.endIndex)
        else {
            Issue.record("attention menu block not found")
            return []
        }
        let endIndex =
            source.range(of: marker, range: attentionStart.upperBound..<source.endIndex)?.lowerBound
            ?? source.endIndex
        let block = String(source[attentionStart.upperBound..<endIndex])
        let regex = try? NSRegularExpression(pattern: #"style="color:#([0-9A-Fa-f]{6})""#)
        var inks: [UInt32] = []
        guard let regex else {
            Issue.record("color regex failed to compile")
            return inks
        }
        for match in regex.matches(in: block, range: NSRange(block.startIndex..., in: block)) {
            guard match.numberOfRanges >= 2,
                let hexRange = Range(match.range(at: 1), in: block),
                let value = UInt32(block[hexRange], radix: 16)
            else { continue }
            inks.append(value)
        }
        return inks
    }

    /// The artboard is regenerated by `Design/_gen_menubar.py`; the test reads it from the package root.
    private static func artboard() throws -> String {
        let root = URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent()
            .deletingLastPathComponent()
            .deletingLastPathComponent()
        let url = root.appending(path: "Design/MenuBar.dc.html")
        return try String(contentsOf: url, encoding: .utf8)
    }

    @Test("the formula matches the published extremes")
    func formula() {
        #expect(abs(ratio(0x00_0000, 0xFF_FFFF) - 21) < 0.01)
        #expect(ratio(0x12_3456, 0x12_3456) == 1)
        #expect(composite(0xFF_FFFF, alpha: 0.5, over: 0x00_0000) == 0x80_8080)
    }

    @Test("the menu's translucent fill on the darkest gradient stop is the worst case for dark text")
    func darkestIsTheLimit() {
        let bright = Self.background(forStop: Self.brightestStop)
        let middle = Self.background(forStop: Self.middleStop)
        let dark = Self.background(forStop: Self.darkestStop)
        #expect(luminance(bright) > luminance(middle))
        #expect(luminance(middle) > luminance(dark))
    }

    /// The artboard has exactly two text-coloured rows in the attention menu: the status and the recovery.
    @Test("the attention menu has two text-coloured rows")
    func twoTextRows() throws {
        let inks = Self.attentionInks(in: try Self.artboard())
        #expect(inks.count == 2, "expected 2 text rows, found \(inks.count)")
    }

    /// Each text colour clears WCAG AA on every composited background the gradient can produce.
    @Test(
        "the attention text clears 4.5:1 on every composited menu surface",
        arguments: [0x6E_909E, 0x44_6370, 0x27_3840])
    func attentionClears(stop: UInt32) throws {
        let inks = Self.attentionInks(in: try Self.artboard())
        guard let ink = inks.first else {
            Issue.record("attention row missing")
            return
        }
        let ground = Self.background(forStop: stop)
        let r = ratio(ink, ground)
        let inkHex = String(ink, radix: 16)
        let groundHex = String(ground, radix: 16)
        #expect(r >= 4.5, "attention ink #\(inkHex) on #\(groundHex) is \(r)")
    }

    @Test(
        "the recovery text clears 4.5:1 on every composited menu surface",
        arguments: [0x6E_909E, 0x44_6370, 0x27_3840])
    func recoveryClears(stop: UInt32) throws {
        let inks = Self.attentionInks(in: try Self.artboard())
        guard inks.count >= 2 else {
            Issue.record("recovery row missing")
            return
        }
        let ink = inks[1]
        let ground = Self.background(forStop: stop)
        let r = ratio(ink, ground)
        let inkHex = String(ink, radix: 16)
        let groundHex = String(ground, radix: 16)
        #expect(r >= 4.5, "recovery ink #\(inkHex) on #\(groundHex) is \(r)")
    }
}
